"""Initial ticket tables

Revision ID: fdabfafdf74b
Revises: 
Create Date: 2026-04-07 10:32:30.524442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdabfafdf74b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('round_id', sa.String(length=50), nullable=False),
    sa.Column('total_wager', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_agent_id'), 'tickets', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tickets_short_code'), 'tickets', ['short_code'], unique=True)
    op.create_table('ticket_bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('bet_target', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_bets')
    op.drop_index(op.f('ix_tickets_short_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_agent_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
