
services:
  # --------------------------------------------------------
  # 1. L'API Gateway : Traefik
  # --------------------------------------------------------
  traefik:
    image: traefik:v2.10
    container_name: casino_gateway
    command:
      # Active l'écoute de Docker (Traefik va scanner les autres conteneurs)
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Ne pas exposer par défaut tous les conteneurs (seulement ceux qu'on choisit)
      - "--providers.docker.exposedbydefault=false"
      # Point d'entrée pour le web (Port 80)
      - "--entrypoints.web.address=:80"
      # Active le dashboard de Traefik (très utile pour débugger)
      - "--api.insecure=true"
      # Provider fichier (pour quand le provider docker fait des siennes)
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--providers.file.watch=true"
    user: root
    ports:
      - "80:80"       # Le port HTTP principal de ton backend
      - "8080:8080"   # Le dashboard d'administration de Traefik
    volumes:
      # Permet à Traefik de discuter avec Docker pour découvrir les services
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro"
    networks:
      - casino_network

  # --------------------------------------------------------
  # 2. La Base de Données : PostgreSQL 16
  # --------------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: casino_db
    environment:
      POSTGRES_USER: casino_admin
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: casino_agent_db
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
    networks:
      - casino_network

  # --------------------------------------------------------
  # 3. Le Cache & Message Broker : Redis 7
  # --------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: casino_redis
    # ports:
    #   - "6379:6379"
    networks:
      - casino_network

  # --------------------------------------------------------
  # 4. Le Microservice Agent (Anciennement Wallet)
  # --------------------------------------------------------
  agent-service:
    build:
      context: ./services/agent-service
    container_name: casino_agent_api
    command: sh -c "sleep 10 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    networks:
      - casino_network
    environment:
      - JWT_SECRET=MonSuperSecretCasino2026!NePasPartager
      - ADMIN_API_KEY=CleSuperSecreteBackoffice2026
      - ROOT_PATH=/api/agents
    volumes:
      - ./services/agent-service:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent.entrypoints=web"
      - "traefik.http.routers.agent.rule=PathPrefix(`/api/agents`)"
      - "traefik.http.services.agent.loadbalancer.server.port=8000"
      - "traefik.http.routers.agent.priority=100"

  # --------------------------------------------------------
  # 5. Le Microservice Ticket
  # --------------------------------------------------------
  ticket-service:
    build:
      context: ./services/ticket-service
    container_name: casino_ticket_api
    command: sh -c "sleep 10 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
      - redis
    networks:
      - casino_network
    environment:
      - REDIS_URL=redis://casino_redis:6379/0
      - JWT_SECRET=MonSuperSecretCasino2026!NePasPartager
      - ADMIN_API_KEY=CleSuperSecreteBackoffice2026
      - ROOT_PATH=/api/tickets
    volumes:
      - ./services/ticket-service:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ticket.entrypoints=web"
      - "traefik.http.routers.ticket.rule=PathPrefix(`/api/tickets`)"
      - "traefik.http.services.ticket.loadbalancer.server.port=8000"
      - "traefik.http.routers.ticket.priority=100"

  # --------------------------------------------------------
  # 6. Moteur de Roulette (State Machine + Redis)
  # --------------------------------------------------------
  game-roulette-service:
    build:
      context: ./services/game-roulette-service
    container_name: casino_roulette_engine
    command: sh -c "sleep 10 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
      - redis
    networks:
      - casino_network
    environment:
      - REDIS_URL=redis://casino_redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://casino_admin:super_secret_password@postgres:5432/casino_roulette_db
    volumes:
      - ./services/game-roulette-service:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.roulette.loadbalancer.server.port=8000"

  # --------------------------------------------------------
  # 7. Interface d'Administration : Backoffice (React)
  # --------------------------------------------------------
  backoffice-web:
    build: 
      context: ./services/backoffice
    container_name: casino_backoffice
    networks:
      - casino_network
    volumes:
      - ./services/backoffice:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backoffice.entrypoints=web"
      - "traefik.http.routers.backoffice.rule=PathPrefix(`/`)"
      - "traefik.http.services.backoffice.loadbalancer.server.port=5173"
      - "traefik.http.routers.backoffice.priority=1"

  # --------------------------------------------------------
  # 9. Interface Agent : Point de Vente (React)
  # --------------------------------------------------------
  agent-web:
    build: 
      context: ./services/agent-web
    container_name: casino_agent_web
    networks:
      - casino_network
    volumes:
      - ./services/agent-web:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent-web.entrypoints=web"
      - "traefik.http.routers.agent-web.rule=PathPrefix(`/agents/pos`)"
      - "traefik.http.services.agent-web.loadbalancer.server.port=5173"
      - "traefik.http.routers.agent-web.priority=10"


networks:
  casino_network:
    driver: bridge

volumes:
  postgres_data:

