http:
  routers:
    agent-api-router:
      rule: "PathPrefix(`/api/agents`)"
      service: agent-service
      priority: 100
      entryPoints:
        - web

    ticket-api-router:
      rule: "PathPrefix(`/api/tickets`)"
      service: ticket-service
      priority: 100
      entryPoints:
        - web

    roulette-api-router:
      rule: "PathPrefix(`/api/roulette`)"
      service: roulette-service
      priority: 100
      middlewares:
        - roulette-stripprefix
      entryPoints:
        - web

    roulette-ws-router:
      rule: "PathPrefix(`/ws/roulette`)"
      service: roulette-service
      priority: 100
      entryPoints:
        - web

    agent-web-router:
      rule: "PathPrefix(`/agents/pos`)"
      service: agent-web-service
      priority: 10
      entryPoints:
        - web

    # Catch-all pour le backoffice
    backoffice-router:
      rule: "PathPrefix(`/`)"
      service: backoffice-service
      priority: 1
      entryPoints:
        - web

  middlewares:
    agent-stripprefix:
      stripPrefix:
        prefixes:
          - "/agents/pos"
    roulette-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/roulette"

  services:
    agent-service:
      loadBalancer:
        servers:
          - url: "http://casino_agent_api:8000"

    ticket-service:
      loadBalancer:
        servers:
          - url: "http://casino_ticket_api:8000"

    roulette-service:
      loadBalancer:
        servers:
          - url: "http://casino_roulette_engine:8000"

    agent-web-service:
      loadBalancer:
        servers:
          - url: "http://casino_agent_web:5173"

    backoffice-service:
      loadBalancer:
        servers:
          - url: "http://casino_backoffice:5173"
